name: Dispatch
on:

  workflow_dispatch:
    inputs:
      CONCURRENCY_KEY:
        description: 'concurrency key to use in this workflow'
        type: string
        required: false
        default: 'demo'  

  repository_dispatch:
    types: [certificate-removal]
  
  pull_request:  
  
  push:
    branches:
     - master  

concurrency: "${{ github.event.inputs.CONCURRENCY_KEY-cert || github.sha }}"

env:
  AKAMAI_CLI_VERSION: "v1.5.4"
  EDGERC_FILE: "/home/runner/.edgerc"


jobs:
  dispatch-test:
    if: ${{ github.event_name != 'push' || github.event.inputs.CONCURRENCY_KEY != '' }}
    name: repository dispatch test - ${{ github.event.inputs.CONCURRENCY_KEY || github.sha }}
    runs-on: ubuntu-latest
    steps:

      # Install akamai cli and subcommands
      - name: Install cli
        shell: bash
        run: |
          set -x
          # Download Akamai CLI and copy to /usr/local/bin
          wget https://github.com/akamai/cli/releases/download/"${AKAMAI_CLI_VERSION}"/akamai-"${AKAMAI_CLI_VERSION}"-linuxamd64
          chmod +x akamai-"${AKAMAI_CLI_VERSION}"-linuxamd64
          mv akamai-"${AKAMAI_CLI_VERSION}"-linuxamd64 /usr/local/bin/akamai
          
          # echo out the version to show successful installation
          akamai --version
          
          sleep 60
          
          # debug
          echo "enrollment_id: ${{ github.event.client_payload.enrollment_id }}"
